Create README.md
santosomar/eol-eos pull request #17
Opened 2023-05-03 04:33 UTC by santosomar

Fixes #11 

Creating a more detailed draft documentation for the schema

2023-05-04 22:11 UTC, tschmidtb51 requested changes
Some minor comments

2023-05-04 22:11 UTC, tschmidtb51 commented on schema/README.md
> +
```suggestion
*Note: The exact usage and proper identifying method of this field is currently under discussion in the community (see #6). As a [CSAF](https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html) issuing party, you could use the value `/document/publisher/namespace`.*

```

2023-05-04 22:11 UTC, tschmidtb51 commented on schema/README.md
> +
```suggestion
*Note: The exact usage and proper identifying method of this field is currently under discussion in the community (see #22). If you have an SBOM that you provide for download at a specific link and that one is stable, the download URL could be used as identifier.*

```

2023-05-04 22:11 UTC, tschmidtb51 commented on schema/README.md
> +
```suggestion
    *Note: The exact usage and proper identifying method of this field is currently under discussion in the community (see #22). If you have an SBOM that you provide for download at a specific link and that one is stable, the download URL could be used as identifier.*

```

2023-05-04 22:11 UTC, tschmidtb51 commented on schema/README.md
> +8. **productVersion**: This property contains the version or release information of the product. It is a string with a minimum length of 1 character and references the `productVersion_t` definition.
```suggestion
8. **productVersion**: This property contains the version or release information of the product. It is a string with a minimum length of 1 character and references the `productVersion_t` definition. This SHALL not contain a version range.

2023-05-04 22:11 UTC, tschmidtb51 commented on schema/README.md
> +    - **productVersion**: Contains the version or release information of the replacement product. It is a string with a minimum length of 1 character and references the `productVersion_t` definition.
```suggestion
    - **productVersion**: Contains the version or release information of the product. It is a string with a minimum length of 1 character and references the `productVersion_t` definition. This SHALL not contain a version range.

2023-05-05 02:08 UTC, santosomar commented
Thank you @tschmidtb51 ! I incorporated your suggested changes.

2023-05-05 02:09 UTC, merged